<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $guarded = [];
    private static $category;
    public function getRouteKeyName()
    {
        //return parent::getKeyName(); // TODO: Change the autogenerated stub
        return 'slug';
    }

    public static function newCategory($request)
    {
        self::$category = new Category();
        self::$category->name = $request->name;
        self::$category->slug = str_slug($request->slug);
        self::$category->save();
    }
    public static function updateCategory($request,$category)
    {
       $category->name = $request->name;
       $category->slug = str_slug($request->slug);
       $category->save();
    }
    public function getPathAttribute()
    {
        return asset('/api/category/'.$this->slug);
    }
}
